GENCCODE_ASSEMBLY_TYPE=-a gcc
SO=so
SOBJ=so
A=a
LIBPREFIX=lib
LIB_EXT_ORDER=.58.2
COMPILE=/data/jenkins2/workspace/OneCloudFirmware1_AP_192.168.126.224/output/mesongxl_p230_5.0/host/usr/bin/aarch64-linux-gnu-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1 -DU_HAVE_STRTOD_L=1  -DU_ATTRIBUTE_DEPRECATED= -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -std=c99 -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -c
LIBFLAGS=-I/usr/include -DPIC -fPIC
GENLIB=/data/jenkins2/workspace/OneCloudFirmware1_AP_192.168.126.224/output/mesongxl_p230_5.0/host/usr/bin/aarch64-linux-gnu-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -std=c99 -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings    -shared -Wl,-Bsymbolic
LDICUDTFLAGS=
LD_SONAME=-Wl,-soname -Wl,
RPATH_FLAGS=
BIR_LDFLAGS=-Wl,-Bsymbolic
AR=/data/jenkins2/workspace/OneCloudFirmware1_AP_192.168.126.224/output/mesongxl_p230_5.0/host/usr/bin/aarch64-linux-gnu-ar
ARFLAGS=r
RANLIB=/data/jenkins2/workspace/OneCloudFirmware1_AP_192.168.126.224/output/mesongxl_p230_5.0/host/usr/bin/aarch64-linux-gnu-ranlib
INSTALL_CMD=/usr/bin/install -c
