#!/bin/sh

if [ -f /etc/init.d/rc.modules ]; then
        /etc/init.d/rc.modules
fi

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

# add for logrotate tool
# crond's default Cron dir:/var/spool/cron/crontabs 
crond -c /etc/crontabs

