#!/bin/sh 
# 
# Starts the inetd daemon. 
# 
 
NAME=inetd 
DAEMON=/usr/sbin/$NAME 
PIDFILE=/var/run/$NAME.pid 
 
case "$1" in 
  start) 
	echo -n "Starting $NAME: " 
	start-stop-daemon -S -q -m -p $PIDFILE -b -x $DAEMON -- -f && echo "OK" || echo "Failed" 
	;; 
  stop) 
	echo -n "Stopping $NAME: " 
	start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed" 
	rm -f $PIDFILE 
	;; 
  restart|reload) 
	$0 stop 
	$0 start 
	;; 
  *) 
	echo $"Usage: $0 {start|stop|restart}" 
	exit 1 
esac 
 
exit $? 
 
