#!/bin/sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/thunder/lib:/lib:/usr/lib
[ -f /tmp/dlna.conf ] || exit 0

#mkdir -p /var/log/dlna

start() {
	printf "Starting DLNA services: "
	/thunder/bin/dlna &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Shutting down DLNA services: "
	kill -9 `pidof dlna`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	rm -rf /var/run/dlna.pid
}

restart() {
	stop
	start
}

reload() {
    printf "Reloading dlna.conf file: "
	kill -HUP `pidof dlna`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
